# .readthedocs.yaml
version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3.11"

sphinx:
  configuration: docs/_source/conf.py

python:
  install:
  - method: pip
    path: .
  - requirements: docs/requirements.txt
