"""``jaeger utils`` command group.

Auxiliary data-prep, conversion, OOD-generation, and model-utility commands.
Heavy dependencies are imported lazily inside each command body so that
``jaeger --help`` stays fast and quiet.
"""

from __future__ import annotations

import copy
import logging
import math
import warnings
from pathlib import Path

import click

from jaeger.commands.convert_graph import convert_graph

logger = logging.getLogger("Jaeger")


@click.group(context_settings=dict(help_option_names=["-h", "--help"]))
@click.pass_context
def utils(obj):
    """
    tool chain with auxiliary functions
    """
    pass


def _deprecated_alias(command: click.Command, old_name: str) -> None:
    """Register *command* under *old_name* as a hidden, deprecated alias.

    The alias reuses the command's options and callback but emits a
    deprecation warning and is hidden from ``--help``.
    """
    alias = copy.copy(command)
    alias.name = old_name
    alias.hidden = True
    new_name = command.name
    alias.help = f"Deprecated alias for `{new_name}`."
    alias.short_help = f"Deprecated alias for `{new_name}`."
    original_callback = command.callback

    def callback(*args, **kwargs):
        logger.warning(
            f"'jaeger utils {old_name}' is deprecated; "
            f"use 'jaeger utils {new_name}' instead."
        )
        return original_callback(*args, **kwargs)

    alias.callback = callback
    utils.add_command(alias, old_name)


@utils.command(
    name="generate-ood",
    context_settings=dict(show_default=True),
    help="""
            Generate out-of-distribution (OOD) sequences from in-distribution
            (ID) sequences using synthetic perturbations.

            The output is an OOD-only CSV file that can be converted to NPZ with
            ``jaeger utils encode-npz`` and then combined with an ID NPZ using
            ``jaeger utils combine-reliability``.

            usage
            -----

            jaeger utils generate-ood -i train.csv -o train_ood.csv \\
                --crop-size 3331 --multiplier 1.0 --shuffle-proportion 0.75

        """,
)
@click.option(
    "-i",
    "--input",
    type=click.Path(exists=True),
    required=True,
    help="Path to input CSV file (label,sequence[,seq_id])",
)
@click.option("-o", "--output", type=str, required=True, help="Path to output CSV file")
@click.option(
    "--crop-size",
    type=int,
    default=None,
    help="Crop size in codons for generated OOD sequences (default: use input length)",
)
@click.option(
    "--crop-units",
    type=click.Choice(["codon", "nucleotide"], case_sensitive=False),
    default="codon",
    show_default=True,
    help="Units for --crop-size",
)
@click.option(
    "--multiplier",
    type=float,
    default=1.0,
    show_default=True,
    help="Number of OOD sequences to generate per input sequence",
)
@click.option(
    "--shuffle-proportion",
    type=float,
    default=0.75,
    show_default=True,
    help="Proportion of OOD sequences generated by shuffling (rest split across other perturbations)",
)
@click.option(
    "--pre-shuffle",
    is_flag=True,
    default=False,
    show_default=True,
    help="Shuffle sequence before applying non-shuffle perturbations",
)
@click.option(
    "--shuffle-mode",
    type=click.Choice(["random", "dinuc", "kmer"], case_sensitive=False),
    multiple=True,
    default=("dinuc", "random"),
    show_default=True,
    help="Shuffle modes to use (can be given multiple times)",
)
@click.option(
    "--kmer-k",
    type=int,
    default=2,
    show_default=True,
    help="K for kmer shuffle mode",
)
@click.option(
    "--subseq-repeat/--no-subseq-repeat",
    default=True,
    show_default=True,
    help="Enable subsequence repeat perturbation",
)
@click.option(
    "--tandem-repeat/--no-tandem-repeat",
    default=True,
    show_default=True,
    help="Enable tandem repeat perturbation",
)
@click.option(
    "--n-stretch/--no-n-stretch",
    default=True,
    show_default=True,
    help="Enable N-stretch perturbation",
)
@click.option(
    "--mix/--no-mix",
    default=True,
    show_default=True,
    help="Enable mix (chimera) perturbation",
)
@click.option(
    "--gc-shift/--no-gc-shift",
    default=False,
    show_default=True,
    help="Enable directed G+C-shift perturbation (AT<->GC mutagenesis)",
)
@click.option(
    "--gc-shift-rate-range",
    type=float,
    nargs=2,
    default=(0.05, 0.20),
    show_default=True,
    help="Mutation-rate range for gc_shift",
)
@click.option(
    "--pad-truncate/--no-pad-truncate",
    default=False,
    show_default=True,
    help="Enable truncate-and-pad perturbation (mirrors short-contig padding "
    "at inference; pads with 'M')",
)
@click.option(
    "--iid-random/--no-iid-random",
    default=False,
    show_default=True,
    help="Enable iid random-sequence perturbation (structureless OOD)",
)
@click.option(
    "--iid-random-gc-range",
    type=float,
    nargs=2,
    default=(0.25, 0.75),
    show_default=True,
    help="G+C range for iid_random sequences",
)
@click.option(
    "--pad-length-range",
    type=int,
    nargs=2,
    default=(500, 1900),
    show_default=True,
    help="Retained-length range (nt) for pad_truncate",
)
@click.option(
    "--window-fraction",
    type=float,
    default=0.25,
    show_default=True,
    help="Window fraction for subseq_repeat and tandem_repeat",
)
@click.option(
    "--motif-length-range",
    type=int,
    nargs=2,
    default=(3, 10),
    show_default=True,
    help="Motif length range for tandem_repeat",
)
@click.option(
    "--num-repeats",
    type=int,
    default=20,
    show_default=True,
    help="Number of motif repeats for tandem_repeat",
)
@click.option(
    "--n-fraction-range",
    type=float,
    nargs=2,
    default=(0.3, 1.0),
    show_default=True,
    help="N fraction range for n_stretch",
)
@click.option(
    "--max-stretches",
    type=int,
    default=3,
    show_default=True,
    help="Maximum N stretches for n_stretch",
)
@click.option(
    "--generation-workers",
    type=int,
    default=None,
    help="Number of parallel workers for synthetic generation",
)
@click.option(
    "--generation-chunk-size",
    type=int,
    default=10000,
    show_default=True,
    help="Chunk size for synthetic generation",
)
@click.option(
    "--source-sample-size",
    type=int,
    default=None,
    help="Subsample input sequences before generation (for very large inputs)",
)
def ood_data(**kwargs):
    from jaeger.dataops.ood import generate_ood_csv_core

    generate_ood_csv_core(**kwargs)


@utils.command(
    name="combine-reliability",
    context_settings=dict(show_default=True),
    help="""Combine an ID NPZ and an OOD NPZ into a single reliability NPZ.

            usage
            -----

            jaeger utils combine-reliability \\
                --id-npz train_id.npz --ood-npz train_ood.npz -o reliability_train.npz
        """,
)
@click.option(
    "--id-npz",
    type=click.Path(exists=True),
    required=True,
    help="Path to ID (in-distribution) NPZ file",
)
@click.option(
    "--ood-npz",
    type=click.Path(exists=True),
    required=True,
    help="Path to OOD (out-of-distribution) NPZ file",
)
@click.option(
    "-o",
    "--output",
    type=str,
    required=True,
    help="Path to output combined reliability NPZ file",
)
@click.option(
    "--shuffle-seed",
    type=int,
    default=None,
    help="Seed for shuffling the combined dataset",
)
@click.option(
    "--balance-ratio",
    type=float,
    default=None,
    help="Target ID:OOD ratio. Downsamples the ID side to "
    "balance-ratio * n_ood samples (e.g. 1.0 = balanced).",
)
def combine_reliability_data(**kwargs):
    """Combine ID and OOD NPZ files into a reliability dataset."""
    from jaeger.commands.utils import combine_reliability_data_core

    combine_reliability_data_core(**kwargs)


@utils.command(
    name="inspect-npz",
    context_settings=dict(show_default=True),
    help="""Inspect a Jaeger NPZ dataset and print a summary.

            Shows keys, shapes, dtypes, label distribution, and crop/format
            metadata for both sharded and non-sharded NPZ files.

            usage
            -----

            jaeger utils inspect-npz -i train.npz
        """,
)
@click.option(
    "-i",
    "--input",
    type=click.Path(exists=True),
    required=True,
    help="Path to the NPZ file",
)
@click.option(
    "--labels/--no-labels",
    default=True,
    show_default=True,
    help="Compute the label distribution (disable for very large files)",
)
def inspect_npz(**kwargs):
    """Inspect a Jaeger NPZ dataset and print a summary."""
    from jaeger.commands.utils import inspect_npz_core

    inspect_npz_core(**kwargs)


@utils.command(
    name="sample-fragments",
    context_settings=dict(show_default=True),
    help="""
            Simulate a metagenome assembly from contigs/genomes given fragment size range.

            usage
            -----

            jaeger utils sample-fragments [OPTIONS] -i contigs.fasta -o fragmented_contigs.fasta

        """,
)
@click.option(
    "-i",
    "--input",
    type=click.Path(exists=True),
    required=True,
    help="Path to input file",
)
@click.option("-o", "--output", type=str, required=True, help="Path to output file")
@click.option("--minlen", type=int, required=True, help="min fragment size")
@click.option("--maxlen", type=int, required=True, help="max fragment size")
@click.option(
    "--overlap", type=int, required=False, help="overlap between fragments", default=0
)
@click.option("--shuffle", is_flag=True, help="enable shuffling.")
@click.option(
    "--coverage",
    type=float,
    required=False,
    default=None,
    help="Switch to coverage-based sampling: sample fragments until "
    "coverage * genome_length bases are reached per sequence.",
)
@click.option(
    "--circular",
    is_flag=True,
    required=False,
    default=False,
    help="Treat sequences as circular (fragments may wrap around the ends).",
)
@click.option(
    "--max-n-prop",
    type=float,
    required=False,
    default=0.3,
    help="Maximum proportion of Ns allowed in a fragment.",
)
@click.option(
    "--seed",
    type=int,
    required=False,
    default=None,
    help="Random seed for reproducible fragment sampling.",
)
def fragment(**kwargs):
    """Sample random fragments from genomes to mimic metagenome assemblies."""
    from jaeger.dataops.split import split_core

    split_core(**kwargs)


@utils.command(
    name="mask-sequences",
    context_settings=dict(show_default=True),
    help="""
            Gradually mask or mutate random positions in a given fasta file.

            usage
            -----

            jaeger utils mask-sequences [OPTIONS] -i contigs.fasta -o masked_contigs.fasta

            "CACTACACGTACG" -> "NACNNACGTNNG"   (hard-mask to N)

            jaeger utils mask-sequences [OPTIONS] -i contigs.fasta -o mutated_contigs.fasta --mutate

            "CACTACACGTACG" -> "TACTGAACGTTGT"  (replace with random nucleotides)
        """,
)
@click.option(
    "-i",
    "--input",
    type=click.Path(exists=True),
    required=True,
    help="Path to input file",
)
@click.option("-o", "--output", type=str, required=True, help="Path to output file")
@click.option(
    "--minperc",
    type=float,
    required=False,
    help="min fraction of positions to mask (0.0-1.0)",
    default=0.0,
)
@click.option(
    "--maxperc",
    type=float,
    required=False,
    help="max fraction of positions to mask (0.0-1.0)",
    default=1.0,
)
@click.option(
    "--step",
    type=float,
    required=False,
    help="fraction of positions to mask in each iteration",
    default=0.01,
)
@click.option(
    "--mutate",
    is_flag=True,
    required=False,
    help="replace with random nucleotides without masking",
    default=False,
)
@click.option(
    "--seed",
    type=int,
    required=False,
    default=None,
    help="Random seed for reproducible masking/mutation",
)
def mask(**kwargs):
    """Gradually mask or mutate random positions in a FASTA file."""
    from jaeger.commands.utils import mask_core

    if kwargs.get("maxperc") < kwargs.get("minperc"):
        raise click.BadParameter("maxperc can not be lower than minperc")

    mask_core(**kwargs)


@utils.command(
    name="build-dataset",
    context_settings=dict(show_default=True),
    help="""
            Generate a non-redundant fragment database from fasta file for training/validating
            fragment models

            usage
            -----

            jaeger utils build-dataset [OPTIONS] -i contigs.fasta -o fragmented_contigs

        """,
)
@click.option(
    "-i",
    "--input",
    type=click.Path(exists=True),
    required=True,
    help="Path to input file",
)
@click.option("-o", "--output", type=str, required=True, help="Path to output prefix")
@click.option("--class", "class_id", type=int, required=False, help="class label")
@click.option(
    "--valperc",
    type=float,
    required=False,
    help="fraction of fragments to include in validation set",
    default=0.1,
)
@click.option(
    "--trainperc",
    type=float,
    required=False,
    help="fraction of fragments to include in train set",
    default=0.8,
)
@click.option(
    "--testperc",
    type=float,
    required=False,
    help="fraction of fragments to include in test set",
    default=0.1,
)
@click.option(
    "--maxiden",
    type=float,
    required=False,
    help="max identity between any two fragments",
    default=0.6,
)
@click.option(
    "--maxcov",
    type=float,
    required=False,
    help="max coverage between any two fragments",
    default=0.6,
)
@click.option(
    "--fraglen", type=int, required=False, help="max fragment length", default=2048
)
@click.option(
    "--overlap",
    type=int,
    required=False,
    help="max overlap between sequences",
    default=1024,
)
@click.option(
    "--intype",
    type=click.Choice(["CSV", "FASTA"], case_sensitive=False),
    required=False,
    help="input type",
    default="CSV",
)
@click.option(
    "--class-col",
    "--class_col",
    "class_col",
    type=int,
    required=False,
    help="csv col with class id",
)
@click.option(
    "--seq-col",
    "--seq_col",
    "seq_col",
    type=int,
    required=False,
    help="csv col with sequence",
)
@click.option(
    "--outtype",
    type=click.Choice(["CSV", "FASTA"], case_sensitive=False),
    required=False,
    help="output type",
    default="CSV",
)
@click.option(
    "--method",
    type=click.Choice(["ANI", "AAI"], case_sensitive=False),
    required=False,
    help="dereplication method",
    default="ANI",
)
@click.option(
    "--seed",
    type=int,
    required=False,
    default=None,
    help="Random seed for reproducible train/val/test splitting",
)
def dataset(**kwargs):
    """Generate a non-redundant fragment database from fasta file for training/validating
    fragment models"""
    from jaeger.commands.utils import dataset_core

    intype = kwargs.get("intype", "").upper()

    match intype:
        case "CSV":
            if not (
                kwargs.get("class_col") is not None
                and kwargs.get("seq_col") is not None
            ):
                raise click.UsageError(
                    "For CSV input, you must specify both --seq-col and --class-col."
                )
        case "FASTA":
            if kwargs.get("class_id") is None:
                raise click.UsageError("For FASTA input, you must specify --class.")
        case _:
            raise click.UsageError("Invalid input type: must be 'CSV' or 'FASTA'.")

    # build_dataset reads the ``class`` kwarg; map the click-safe ``class_id``.
    kwargs["class"] = kwargs.pop("class_id", None)
    dataset_core(**kwargs)


@utils.command(
    name="convert-sequences",
    context_settings=dict(show_default=True),
    help="""
            Convert training data between CSV and FASTA formats

            usage                                                                      
            -----                                                                      

            jaeger utils convert-sequences --itype FASTA -i contigs.fasta -o fragmented_contigs.csv

        """,
)
@click.option(
    "-i",
    "--input",
    type=click.Path(exists=True),
    required=True,
    help="Path to input file",
)
@click.option("-o", "--output", type=str, required=True, help="Path to output file")
@click.option(
    "--itype",
    type=click.Choice(["FASTA", "CSV"], case_sensitive=False),
    required=True,
    help="input file type",
)
def convert(**kwargs):
    """convert CSV to FASTA and FASTA to CSV"""
    from jaeger.commands.utils import convert_core

    convert_core(**kwargs)


@utils.command(
    name="encode-npz",
    context_settings=dict(show_default=True),
    help="""
            Convert training data to an optimized NPZ dataset for faster loading.
            Preprocesses CSV data once so training can skip live preprocessing.

            usage
            -----

            jaeger utils encode-npz -i train.csv -o train.npz --format translated

            Supported formats:
              nucleotide  - 2-strand integer or one-hot nucleotide encoding
              translated  - 6-frame integer or one-hot codon encoding
              both        - store both nucleotide and translated arrays
        """,
)
@click.option(
    "-i",
    "--input",
    type=click.Path(exists=True),
    required=True,
    help="Path to input CSV file (label,sequence)",
)
@click.option(
    "-o",
    "--output",
    type=str,
    required=True,
    help="Path to output .npz file",
)
@click.option(
    "--format",
    type=click.Choice(
        ["nucleotide", "translated", "both"],
        case_sensitive=False,
    ),
    required=True,
    help="Output representation",
)
@click.option(
    "--crop-size",
    type=int,
    multiple=True,
    default=(500,),
    show_default=True,
    help="Crop length(s); can be given multiple times (see --crop-units)",
)
@click.option(
    "--crop-units",
    type=click.Choice(["codon", "nucleotide"], case_sensitive=False),
    default=None,
    show_default=True,
    help="Units for --crop-size and --stride: codon or nucleotide. "
    "Overrides --units. Defaults to the legacy --units value (nuc).",
)
@click.option(
    "--units",
    type=click.Choice(["nuc", "codon"], case_sensitive=False),
    default=None,
    help="Deprecated alias for --crop-units (nuc = nucleotide).",
)
@click.option(
    "--stride",
    type=int,
    default=0,
    show_default=True,
    help="Step between crops (0 = one crop per sequence; see --crop-units)",
)
@click.option(
    "--overlap",
    type=click.FloatRange(0.0, 1.0, min_open=False, max_open=False),
    default=None,
    show_default=True,
    help="Overlap between crops as a fraction of each crop size (0.0-1.0). Overrides --stride.",
)
@click.option(
    "--max-memory-mb",
    type=int,
    default=None,
    show_default=True,
    help=(
        "Memory budget in MB for encoded output buffers. "
        "If omitted, auto-budget is ~75% of available RAM. "
        "Set to 0 to disable streaming."
    ),
)
@click.option(
    "--pad",
    is_flag=True,
    default=False,
    show_default=True,
    help="Pad all crops to the global maximum length (legacy behavior).",
)
@click.option(
    "--num-classes",
    type=int,
    default=3,
    show_default=True,
    help="Number of classes",
)
@click.option(
    "--num-workers",
    type=int,
    default=None,
    help="Number of parallel workers (default: all CPUs)",
)
@click.option(
    "--one-hot",
    is_flag=True,
    default=False,
    show_default=True,
    help="Output float one-hot tensors instead of integer indices",
)
@click.option(
    "--pad-int",
    type=int,
    default=0,
    show_default=True,
    help="Padding value for integer outputs",
)
@click.option(
    "--codon-map",
    type=click.Choice(
        ["codon_id", "aa_id", "pc5_id", "murphy10_id", "cod_id", "pc2_id"],
        case_sensitive=False,
    ),
    default="codon_id",
    show_default=True,
    help="Codon mapping for translated output",
)
@click.option(
    "--nucleotide-map",
    type=str,
    default=None,
    help='JSON mapping for A, C, G, T, N (default: {"A":1,"G":2,"T":3,"C":4,"N":0})',
)
@click.option(
    "--compress",
    type=click.Choice(
        ["fast", "default", "none"],
        case_sensitive=False,
    ),
    default="fast",
    show_default=True,
    help="NPZ compression level",
)
@click.option(
    "--dtype",
    type=click.Choice(
        ["int8", "uint8", "int16", "int32", "auto"],
        case_sensitive=False,
    ),
    default="auto",
    show_default=True,
    help="Integer dtype for encoded features (auto picks the smallest fitting dtype)",
)
@click.option(
    "--max-length",
    type=int,
    default=5000,
    hidden=True,
    help="Deprecated and ignored",
)
@click.option(
    "--balance-classes",
    is_flag=True,
    default=False,
    show_default=True,
    help=(
        "Deal every class round-robin across output shards so each shard "
        "holds an equal share of every class, and interleave classes within "
        "each shard (avoids class-blocked shards and same-class runs)."
    ),
)
@click.option(
    "--shuffle-seed",
    type=int,
    default=42,
    show_default=True,
    help="Seed for the within-class shuffle used with --balance-classes",
)
@click.option(
    "--target-shards",
    type=int,
    default=None,
    show_default=True,
    help="Tune the streaming memory budget so the output NPZ has approximately "
    "this many shards (forces sharded streaming). Useful when the output will "
    "be combined shard-by-shard with another sharded NPZ.",
)
def optimize_data(**kwargs):
    """Convert CSV training data to an optimized NPZ dataset."""
    from jaeger.commands.utils import optimize_data_core

    optimize_data_core(
        input_path=kwargs.get("input"),
        output_path=kwargs.get("output"),
        format=kwargs.get("format"),
        crop_size=list(kwargs.get("crop_size")),
        stride=kwargs.get("stride"),
        overlap=kwargs.get("overlap"),
        units=kwargs.get("units"),
        crop_units=kwargs.get("crop_units"),
        num_classes=kwargs.get("num_classes"),
        num_workers=kwargs.get("num_workers"),
        one_hot=kwargs.get("one_hot"),
        pad_int=kwargs.get("pad_int"),
        codon_map=kwargs.get("codon_map"),
        nucleotide_map=kwargs.get("nucleotide_map"),
        compress=kwargs.get("compress"),
        dtype=kwargs.get("dtype"),
        max_length=kwargs.get("max_length"),
        max_memory_mb=kwargs.get("max_memory_mb"),
        pad=kwargs.get("pad"),
        balance_classes=kwargs.get("balance_classes"),
        shuffle_seed=kwargs.get("shuffle_seed"),
        target_num_shards=kwargs.get("target_shards"),
    )


@utils.command(
    context_settings=dict(show_default=True),
    help="""Combine multiple model graphs into an ensemble model. Outputs can be summarized with majority voting,
            sum or mean of logits of each model

            usage\n
            -----

            jaeger utils combine-models -i path/to/model1 -i path/to/model2 -i path/to/model3 -c mv
        """,
)
@click.option(
    "-i",
    "--input",
    type=click.Path(exists=True),
    required=True,
    help="Path to saved model",
    multiple=True,
)
@click.option(
    "-o", "--output", type=str, required=True, help="Path to save the ensemble model"
)
@click.option(
    "-c",
    "--comb",
    type=click.Choice(["MV", "SUM", "MEAN", "NONE"], case_sensitive=False),
    required=True,
    help="how to summarize the model outputs "
    "MV: majority voting"
    "SUM: sum of logits"
    "MEAN: Mean of logits"
    "NONE: fallback to mean (keeps a valid SavedModel output)",
)
def combine_models(**kwargs):
    from jaeger.commands.utils_models import combine_models_core

    combine_models_core(**kwargs)


@utils.command(
    name="summarize-predictions",
    context_settings=dict(show_default=True),
    help="""
            Calculate stats from Jaeger output

            usage                                                                      
            -----                                                                      

            jaeger utils summarize-predictions -i jaeger_output.tsv -o jaeger_output_stats
            
        """,
)
@click.option(
    "-i",
    "--input",
    type=click.Path(exists=True),
    required=True,
    help="Path to input .tsv file",
)
@click.option("-o", "--output", type=str, required=True, help="Path to output dir")
def stats(**kwargs):
    """Calculate stats from Jaeger output"""
    from jaeger.commands.utils import stats_core

    stats_core(**kwargs)
    pass


@utils.command(
    context_settings=dict(show_default=True),
    help="""
            Quantize a Jaeger model for faster inference (deprecated).

            This command is deprecated; use
            ``jaeger utils convert-model --mode tflite --quantize <mode>`` instead.

            usage
            -----

            jaeger utils quantize -m default -o ./quantized_models
            jaeger utils quantize -m jaeger_38341_1.4M_fragment -o ./quantized --mode float16
        """,
)
@click.option(
    "-m",
    "--model",
    type=str,
    required=True,
    help="Model name to quantize",
)
@click.option(
    "-o",
    "--output",
    type=click.Path(path_type=Path),
    required=True,
    help="Output directory for the quantized model",
)
@click.option(
    "--mode",
    type=click.Choice(["dynamic", "float16", "full_int8"]),
    default="dynamic",
    help="Quantization mode",
)
@click.option(
    "-v",
    "--verbose",
    count=True,
    help="Verbosity level",
    default=1,
)
def quantize_cmd(**kwargs):
    """Quantize a Jaeger model (deprecated; use convert-model --mode tflite)."""
    warnings.warn(
        "'jaeger utils quantize' is deprecated; use "
        "'jaeger utils convert-model --mode tflite --quantize <mode>' instead.",
        DeprecationWarning,
        stacklevel=2,
    )
    logger.warning(
        "'jaeger utils quantize' is deprecated; use "
        "'jaeger utils convert-model --mode tflite --quantize <mode>' instead."
    )
    convert_graph(
        kwargs["model"],
        kwargs["output"],
        mode="tflite",
        verbose=kwargs.get("verbose", 1),
        quantize=kwargs.get("mode", "dynamic"),
    )


@utils.command(
    name="convert-model",
    context_settings=dict(show_default=True),
    help="""
            Convert a Jaeger SavedModel to an optimized inference graph.

            Supports XLA, TFLite, ONNX, and TensorRT backends.

            usage
            -----

            jaeger utils convert-model -m default -o ./optimized --mode xla
            jaeger utils convert-model -m default -o ./optimized --mode onnx
            jaeger utils convert-model -m default -o ./optimized --mode onnx --int8
        """,
)
@click.option(
    "-m",
    "--model",
    type=str,
    required=True,
    help="Model name to convert",
)
@click.option(
    "-o",
    "--output",
    type=click.Path(path_type=Path),
    required=True,
    help="Output directory for the converted model",
)
@click.option(
    "--mode",
    type=click.Choice(["xla", "tflite", "onnx", "tensorrt"]),
    default="xla",
    help="Conversion mode",
)
@click.option(
    "--int8",
    is_flag=True,
    help="Apply static INT8 quantization (ONNX mode only)",
)
@click.option(
    "--quantize",
    type=click.Choice(["dynamic", "float16", "full_int8"], case_sensitive=False),
    default=None,
    help="TFLite quantization mode (only with --mode tflite). "
    "Replaces the deprecated 'jaeger utils quantize' command.",
)
@click.option(
    "-v",
    "--verbose",
    count=True,
    help="Verbosity level",
    default=1,
)
def convert_graph_cmd(model, output, mode, int8, quantize, verbose):
    """Convert a Jaeger SavedModel to an optimized inference graph."""
    convert_graph(model, output, mode, verbose, int8=int8, quantize=quantize)


@utils.command(
    name="compute-receptive-field",
    context_settings=dict(show_default=True),
    help="""
        Compute and display the 1-D sequence receptive field of a Jaeger model
        described by a YAML config.

        usage
        -----

        jaeger utils compute-receptive-field -c train_config/nn_config.yaml
    """,
)
@click.option(
    "-c",
    "--config",
    type=click.Path(exists=True),
    required=True,
    help="Path to the Jaeger YAML config file.",
)
def receptive_field_cmd(config):
    """Compute the receptive field of a Jaeger model."""
    from pathlib import Path

    from jaeger.utils.misc import load_model_config
    from jaeger.utils.receptive_field import (
        compute_receptive_field,
        receptive_field_summary,
    )

    cfg = load_model_config(Path(config))
    hidden_layers = (
        cfg.get("model", {}).get("representation_learner", {}).get("hidden_layers", [])
    )
    string_processor = cfg.get("model", {}).get("string_processor", {})
    crop_size = string_processor.get("crop_size")
    crop_sizes = string_processor.get("crop_sizes")
    if crop_size is None and crop_sizes:
        crop_size = crop_sizes[0] if isinstance(crop_sizes, list) else crop_sizes

    rf, _ = compute_receptive_field(hidden_layers)
    click.echo(receptive_field_summary(hidden_layers, crop_size=crop_size))
    if crop_size and not math.isinf(rf) and rf > crop_size:
        click.echo(
            f"  Warning: receptive field ({rf}) is larger than the crop size "
            f"({crop_size})."
        )


# ---------------------------------------------------------------------------
# Backward-compatible deprecated aliases (hidden from --help).
# Canonical names follow the verb-object convention; the old names still work.
# ---------------------------------------------------------------------------
_deprecated_alias(ood_data, "ood-data")
_deprecated_alias(combine_reliability_data, "combine-reliability-data")
_deprecated_alias(fragment, "fragment")
_deprecated_alias(mask, "mask")
_deprecated_alias(dataset, "dataset")
_deprecated_alias(convert, "convert")
_deprecated_alias(optimize_data, "optimize-data")
_deprecated_alias(stats, "stats")
_deprecated_alias(convert_graph_cmd, "convert-graph")
_deprecated_alias(receptive_field_cmd, "receptive-field")
_deprecated_alias(receptive_field_cmd, "receptive_field")
