model:
  name: multiscale_rf_mlp
  experiment: multiscale_rf_mlp
  seed: 425425
  classifier_out_dim: 6
  reliability_out_dim: 1
  base_dir: /home/yasas-wijesekara/ssd/Projects/Jaeger_revisions/Jaeger/mutiscale_receptive_field_experiments
  class_label_map:
  - class: bacteria
    label: 0
  - class: phage
    label: 1
  - class: eukarya
    label: 2
  - class: archaea
    label: 3
  - class: plasmid
    label: 4
  - class: virus
    label: 5
  activation: gelu
  mode: training
  embedding:
    use_embedding_layer: true
    input_type: translated
    strands: 2
    frames: 6
    length: null
    input_shape:
    - 6
    - null
    embedding_size: 128
    embedding_regularizer: l2
    embedding_regularizer_w: 1.0e-05
  string_processor:
    data_format: numpy
    seq_onehot: false
    codon: CODON
    codon_id: CODON_ID
    overlap: 0.9
    crop_sizes:
    - 500
    validation_crop_sizes:
    - 500
    validation_overlap: 0.9
    buffer_size: 5000
    shuffle: true
    reshuffle_each_iteration: true
    mutate: false
    mutation_rate: 0.05
    shuffle_frames: false
    masking: false
    classifier_labels:
    - 0
    - 1
    - 2
    - 3
    - 4
    - 5
    classifier_labels_map:
    - 0
    - 1
    - 2
    - 3
    - 4
    - 5
  representation_learner:
    hidden_layers:
    - name: masked_conv1d
      config:
        filters: 128
        kernel_size: 7
        strides: 1
        dilation_rate: 1
        use_bias: true
        activation: null
        kernel_regularizer: l2
        kernel_regularizer_w: 1.0e-05
    - name: masked_layernorm
    - name: activation
      config:
        activation: gelu
    - name: parallel_branches
      config:
        merge: concat
        branches:
        - hidden_layers:
          - name: residual_block
            config:
              use_1x1conv: false
              block_size: 1
              filters: 128
              kernel_size: 5
              dilation_rate: 6
              use_bias: true
              kernel_regularizer: l2
              kernel_regularizer_w: 1.0e-05
              norm_type: masked_layernorm
              alpha_init: 0.01
          pooling: max
        - hidden_layers:
          - name: residual_block
            config:
              use_1x1conv: false
              block_size: 1
              filters: 128
              kernel_size: 5
              dilation_rate: 14
              use_bias: true
              kernel_regularizer: l2
              kernel_regularizer_w: 1.0e-05
              norm_type: masked_layernorm
              alpha_init: 0.01
          pooling: max
        - hidden_layers:
          - name: residual_block
            config:
              use_1x1conv: false
              block_size: 1
              filters: 128
              kernel_size: 5
              dilation_rate: 30
              use_bias: true
              kernel_regularizer: l2
              kernel_regularizer_w: 1.0e-05
              norm_type: masked_layernorm
              alpha_init: 0.01
          pooling: max
        - hidden_layers:
          - name: residual_block
            config:
              use_1x1conv: false
              block_size: 1
              filters: 128
              kernel_size: 5
              dilation_rate: 46
              use_bias: true
              kernel_regularizer: l2
              kernel_regularizer_w: 1.0e-05
              norm_type: masked_layernorm
              alpha_init: 0.01
          pooling: max
    pooling: null
  projection:
    margin: 0.5
    scale: 64
    input_shape: 512
    hidden_layers:
    - name: dense
      config:
        units: 32
        activation: gelu
        use_bias: true
        dtype: float32
        kernel_regularizer: l2
        kernel_regularizer_w: 1.0e-05
    - name: dropout
      config:
        rate: 0.1
    - name: dense
      config:
        units: 256
        activation: gelu
        use_bias: true
        dtype: float32
        kernel_regularizer: l2
        kernel_regularizer_w: 1.0e-05
    - name: dropout
      config:
        rate: 0.1
    - name: dense
      config:
        units: 32
        activation: gelu
        use_bias: true
        dtype: float32
        kernel_regularizer: l2
        kernel_regularizer_w: 1.0e-05
    - name: dropout
      config:
        rate: 0.1
  classifier:
    input_shape: 512
    hidden_layers:
    - name: dropout
      config:
        rate: 0.1
    - name: dense
      config:
        units: 256
        activation: gelu
        use_bias: true
        kernel_regularizer: l2
        kernel_regularizer_w: 1.0e-05
    - name: dropout
      config:
        rate: 0.1
    - name: dense
      config:
        units: 6
        activation: null
        dtype: float32
        use_bias: true
        kernel_regularizer: l2
        kernel_regularizer_w: 1.0e-05
training:
  data_dir: /home/yasas-wijesekara/ssd/Projects/Jaeger_revisions/training/jaeger_train_data
  experiment_root: experiments/experiment_{{ model.experiment }}_{{ model.seed }}
  classifier_dir: '{{ model.base_dir }}/{{ training.experiment_root }}/checkpoints/classifier'
  reliability_dir: '{{ model.base_dir }}/{{ training.experiment_root }}/checkpoints/reliability'
  projection_dir: '{{ model.base_dir }}/{{ training.experiment_root }}/checkpoints/projection'
  classifier_epochs: 10
  reliability_epochs: 0
  projection_epochs: 3
  classifier_train_steps: 10000
  reliability_train_steps: 1000
  classifier_validation_steps: 1000
  reliability_validation_steps: 100
  reliability_data_generation:
    raw_csv_paths:
      train: '{{ training.data_dir }}/train_data_2000_sample.csv'
      val: '{{ training.data_dir }}/val_data_2000_sample.csv'
    output_dir: '{{ model.base_dir }}/{{ training.experiment_root }}/checkpoints/reliability'
    crop_sizes:
    - 500
    units: codon
    synthetic_ood_multiplier: 1.0
    inference_batch_size: 128
    perturbations:
      shuffle:
        enabled: true
        mode: dinuc
      subseq_repeat:
        enabled: true
        window_fraction: 0.25
      tandem_repeat:
        enabled: true
        motif_length_range:
        - 3
        - 10
        window_fraction: 0.25
        num_repeats: 20
      mix: true
  batch_size: 64
  classifier_batch_size: 64
  gradient_accumulation_steps: 1
  projection_batch_size: 64
  reliability_batch_size: 64
  optimizer: adamw
  optimizer_params:
    learning_rate: 0.0003
    clipnorm: 1
  loss_classifier: categorical_crossentropy
  loss_params_classifier:
    from_logits: true
    label_smoothing: 0.1
  classifier_class_weights:
    0: 1.71
    1: 1.9
    2: 1.0
    3: 1.42
    4: 6.4
    5: 5.3
  loss_reliability: binary_crossentropy
  loss_params_reliability:
    from_logits: true
  metrics_classifier:
  - name: categorical_accuracy
    params: null
  - name: macro_f1
    params: null
  metrics_reliability:
  - name: binary_accuracy
    params: null
  - name: auc
    params: null
  callbacks:
    clean_old: true
    directories:
    - '{{ model.base_dir }}/{{ training.experiment_root }}/checkpoints/classifier'
    - '{{ model.base_dir }}/{{ training.experiment_root }}/checkpoints/reliability'
    - '{{ model.base_dir }}/{{ training.experiment_root }}/checkpoints/projection'
    classifier:
    - name: EarlyStopping
      params:
        monitor: val_loss
        patience: 3
        mode: min
        restore_best_weights: true
    - name: ModelCheckpoint
      params:
        filepath: '{{ model.base_dir }}/{{ training.experiment_root }}/checkpoints/classifier/epoch:{epoch:02d}-loss:{val_loss:.2f}.weights.h5'
        monitor: val_loss
        mode: min
        save_weights_only: true
        verbose: 1
        save_best_only: false
    - name: ReduceLROnPlateau
      params:
        monitor: val_loss
        patience: 2
        factor: 0.5
        min_lr: 1.0e-05
    - name: TerminateOnNaN
    - name: CSVLogger
      params:
        filename: '{{ model.base_dir }}/{{ training.experiment_root }}/checkpoints/classifier/training.log'
        separator: ','
        append: true
    projection:
    - name: EarlyStopping
      params:
        monitor: val_loss
        patience: 10
        mode: min
        restore_best_weights: true
    - name: ModelCheckpoint
      params:
        filepath: '{{ model.base_dir }}/{{ training.experiment_root }}/checkpoints/projection/epoch:{epoch:02d}-loss:{val_loss:.2f}.weights.h5'
        monitor: val_loss
        mode: min
        save_weights_only: true
        verbose: 1
        save_best_only: false
    - name: ReduceLROnPlateau
      params:
        monitor: val_loss
        patience: 5
        factor: 0.95
        min_lr: 1e-6
    - name: TerminateOnNaN
    - name: CSVLogger
      params:
        filename: '{{ model.base_dir }}/{{ training.experiment_root }}/checkpoints/projection/training.log'
        separator: ','
        append: true
    reliability:
    - name: EarlyStopping
      params:
        monitor: val_loss
        patience: 5
        mode: min
        restore_best_weights: true
    - name: ModelCheckpoint
      params:
        filepath: '{{ model.base_dir }}/{{ training.experiment_root }}/checkpoints/reliability/epoch:{epoch:02d}-loss:{val_loss:.2f}.weights.h5'
        monitor: val_loss
        mode: min
        save_weights_only: true
        verbose: 1
        save_best_only: false
    - name: ReduceLROnPlateau
      params:
        monitor: val_loss
        patience: 5
        factor: 0.95
        min_lr: 1e-6
    - name: TerminateOnNaN
    - name: CSVLogger
      params:
        filename: '{{ model.base_dir }}/{{ training.experiment_root }}/checkpoints/reliability/training.log'
        separator: ','
        append: true
  model_saving:
    path: '{{ model.base_dir }}/{{ training.experiment_root }}/model'
    save_weights: true
    save_exec_graph: true
  fragment_classifier_data:
    train:
    - class:
      - bacteria
      - phage
      - eukarya
      - archaea
      - virus
      - plasmid
      path:
      - '{{ training.data_dir }}/train_data_1800bp_translated.npz'
      label:
      - 0
      - 1
      - 2
      - 3
      - 4
      - 5
    validation:
    - class:
      - bacteria
      - phage
      - eukarya
      - archaea
      - virus
      - plasmid
      path:
      - '{{ training.data_dir }}/val_data_1800bp_translated.npz'
      label:
      - 0
      - 1
      - 2
      - 3
      - 4
      - 5
  fragment_reliability_data:
    train:
    - class:
      - ood
      - indist
      path:
      - '{{ training.data_dir }}/train_shuffled_ood_translated.npz'
      label:
      - 0
      - 1
    validation:
    - class:
      - ood
      - indist
      path:
      - '{{ training.data_dir }}/val_shuffled_ood_translated.npz'
      label:
      - 0
      - 1
